### ISSUE TITLE
Fix the static_cast branches nonsence

### ISSUE THREAD

**Issue by markrosslonergan** [markrosslonergan/Elephant_Vanishes#11]

**Comment by markrosslonergan** [comment]
Replace entire branch idea with TTreeFormula's

**Comment by GuanqunGe** [comment]
Fixed. See branch [feature/fix_branch_cast](https://github.com/markrosslonergan/Elephant_Vanishes/tree/feature/fix_branch_cast)

**Comment by GuanqunGe** [comment]
Done, please see the newest branch that doesn't have conflicts with master: feature/branch_cast 

Ignore old branch [feature/fix_branch_cast](https://github.com/markrosslonergan/Elephant_Vanishes/tree/feature/fix_branch_cast)!!!
